### ISSUE TITLE
Pending issues:

### ISSUE THREAD

**Issue by Mottie** [CSS-Tricks/The-Printliminator#3]
### Misc
* [ ] Add documentation to wiki pages.

### Hiding elements
* [ ] Target & hide extra `<br>` or `<p></p>`
* [ ] Target elements & set top/bottom margin to zero.

### How to Style?
* [ ] Meter: `<meter low="69" high="80" max="100" value="84">B</meter>` - rendered as a background graphic
* [ ] Progress: `<progress value="70" max="100">70 %</progress>` - show graphic or text?
* [ ] Remove `<kbd>` style in reset?
* [ ] Change `<mark>` to white background in reset ([ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark))?

**Comment by Mottie** [comment]
@chriscoyier Do you have any feedback on the Styles section here?

The other questions are sort of self-explanatory, but meter elements don't show up when printing unless you specifically indicate to print background images (at least in Chrome). I opened a [bug report](https://code.google.com/p/chromium/issues/detail?can=2&q=meter%20element&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&id=526384&thanks=526384&ts=1440855245), but it doesn't seem like much will happen unless a standard is established *sigh*

**Comment by chriscoyier** [comment]
- How do meters print without doing anything? badly? not at all?

- Text seems fine?

- Does the `<kbd>` get display none? That's weird and should not happen.

- Mark element is supposed to kinda highlight stuff right? So maybe a dashed underline or something?

**Comment by Mottie** [comment]
Oh, what I meant was when you apply the print stylesheet (Harjita one), should we add some extra styling to deal with those elements.

* If you don't specify to print background image, the `<meter>` won't print at all. There isn't a simple way to force the meter to print the text, at least in Chrome.
* `<kbd>` have styling... like here <kbd>Shift</kbd>... should we do something with that in the print stylesheet?
* And yeah, the mark element is for highlighting, a dashed underline sounds good.

**Comment by Mottie** [comment]
And as for the HTML5 progress element, the graphic is all that prints, not the text.

To show the text, we could add the following to the print style ([demo](http://jsfiddle.net/Mottie/a3mzuw9g/5/)):

```css
/* printing text of progress */
@media print {
	progress[value] {
		position: relative;
		-webkit-appearance: none;
		-moz-appearance: none;
		appearance: none;
		width: auto;
		height: auto;
		border: none;
		box-shadow: none;
	}
	progress[value]:before {
		content: attr(value) '%';
		position: relative;
		top: -0.2em;
	}
	progress[value]::-webkit-progress-bar {
		background: white none;
	}
	progress[value]::-webkit-progress-value {
		background: white none;
	}
	progress[value]::-moz-progress-bar {
		background: white none;
	}
}
```

But this doesn't appear to work in Firefox :disappointed: 

Maybe we should just leave it as-is.
